### PR TITLE
APEX-22: ability to hide ports

### PR DESCRIPTION
**Pull request by chandnisingh**
Please review. Not to be merged in v3.1.0.

### CODE REVIEW

**Comment by 243826** [comment]
looks good to me.

**Comment by chandnisingh** [comment]
Since 3.1.0 is devel-3, can this be merged?

**Comment by 243826** [comment]
If this is more than review only request, then I can pull it in.

**Comment by chandnisingh** [comment]
Fixed the test case

**Comment by tweise** [comment]
https://github.com/apache/incubator-apex-core/pull/4

**Pull request closed without merging**
