### PR TITLE
Update README.md to redirect to Apache Apex repository

### PR DESCRIPTION
**Pull request by vrozov**

### CODE REVIEW

**Comment by vrozov** [comment]
@tweise please review

**Comment by 243826** [comment]
The first line could be "Apex has moved to a new location, for the most up-to-date source - please visit   https://github.com/apache/incubator-apex-core.git"

And the rest of the file can stay in place and you can add "Apex is now an Apache incubating project." add to the description at a prominent introductory place.

committers already know the location of the commit repository. So better to keep the number of URLs to 1.

**Comment by tweise** [comment]
+1 Vlad, can you adjust the PR please?

**Comment by tweise** [comment]
Thanks Vlad, can you do the same for Malhar also please.

**Pull request merged**
