### PR TITLE
Switch to Java7 and update compiler plugin.

### PR DESCRIPTION
**Pull request by tweise**

### CODE REVIEW

**Comment by PramodSSImmaneni** [comment]
Thomas two tests are failing

Results :

Failed tests: 
  AppPackageTest.starting:49 expected:<0> but was:<1>
  DTCliTest.starting:70 expected:<0> but was:<1>

Tests in error: 
  DTCliTest.finished:90 Runtime java.lang.NullPointerException

Tests run: 226, Failures: 2, Errors: 1, Skipped: 10

**Comment by davidyan74** [comment]
I checked out thomas's branch and it passed all tests.  Pramod, can you do "mvn test -Dtest=DTCliTest" and send me the entire output?

**Comment by PramodSSImmaneni** [comment]
David traced this to a build dependency issue not related to java 7. Merging this. That issue will be looked at separately.

**Comment by davidyan74** [comment]
Pull request #17 fixes this issue.  Please review.

**Pull request merged**
