### PR TITLE
enable semantic versioning

### PR DESCRIPTION
**Pull request by 243826**

### CODE REVIEW

**Comment by 243826** [comment]
the build failed because of autometric change.

**Comment by tweise** [comment]
That's fixed. It was a bad dt-engine-3.0.0.jar in the local .m2.

**Comment by tweise** [comment]
Shouldn't these checks go into a profile that we activate in the CI only to keep the development build light and fast.

**Comment by 243826** [comment]
How much time does it take on your machine?

**Comment by tweise** [comment]
This requires Maven 3.1.0 - was a decision made to no longer support 3.0.5?

```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.5.1:cmp (default) on project dt-api: The plugin com.github.siom79.japicmp:japicmp-maven-plugin:0.5.1 requires Maven version 3.1.0 -> [Help 1]
```

**Comment by tweise** [comment]
Also seeing problems in repeated run of mvn install (without clean):
```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.5.1:cmp (default) on project dt-common: Failed to create directory '/home/hdev/devel/dt/Apex/common/target/japicmp'. 
```

**Comment by 243826** [comment]
This was my bad. Will put a fix for checking the mvn version.

**Comment by 243826** [comment]
This is a bug in the plugin (IMO). I have to raise an issue for getting
this fixed.

BTW, for light and fast development it's more likely that the developer
needs to use 'mvn package' instead 'mvn install'. mvn install also includes
integration-tests and verify phases. verify phase will kick in the semver
checks.

**Comment by tweise** [comment]
Any idea why Maven 3.1.0, any info from the author of the plug-in?

**Pull request merged**
