### PR TITLE
SPOI-5355: included javadoc comments extraction support in archetype

### PR DESCRIPTION
**Pull request by chandnisingh**

### CODE REVIEW

**Comment by davidyan74** [comment]
Chandni has a question on the location of XmlJavadocCommentsExtractor.xsl.  Should it be at the same level as the pom.xml file?  My opinion is that it should not be, but should be in somewhere src, similar to the assemble xml file.

**Comment by ashwinchandrap** [comment]
Makes sense. I am moving the ones in library and contrib
to src/main/resources/. Will send a pull request.

On Tue, Jul 7, 2015 at 2:37 PM, David Yan <notifications@github.com> wrote:

> Chandni has a question on the location of XmlJavadocCommentsExtractor.xsl.
> Should it be at the same level as the pom.xml file? My opinion is that it
> should not be, but should be in somewhere src, similar to the assemble xml
> file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataTorrent/Apex/pull/37#issuecomment-119349890>.
>



-- 

Regards,
Ashwin.

**Comment by ashwinchandrap** [comment]
Please let me know if these is another recommended directory where I should move it to?

**Comment by davidyan74** [comment]
Actually, I don't think it should be in resources since anything in the resources directory will be bundled with the result jar.  The xsl file, just like the assemble xml file, is only useful at build time.

**Comment by chandnisingh** [comment]
Can we not put this under src/assemble?

**Comment by 243826** [comment]
standards: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by ashwinchandrap** [comment]
So seems like src/main/xslt conforms to the standard similar to the antlr example mentioned in the standards url.

**Comment by chandnisingh** [comment]
antr is the name of the plugin.

**Comment by ashwinchandrap** [comment]
True..in case of xslt, the plugin is called xml-maven-plugin and xslt is an execution in it. May be we should go for src/main/xml/ then.

**Comment by ashwinchandrap** [comment]
src/main/xml/xslt/ may be even more concrete.

**Comment by 243826** [comment]
Guys, if this is a tool/config that builds the project, then it looks like
it should not be under src. I checked flink and spark. They have similar
files right by pom.xml.

**Comment by chandnisingh** [comment]
In that case my pull request can be merged. It places this file right by pom.xml

**Comment by davidyan74** [comment]
Chandni is going to add some sample operator that makes use of the javadoc comment extraction in the archetype.

**Pull request closed without merging**
